### ISSUE TITLE
Social links

### ISSUE THREAD

**Issue by mxstbr** [jeddy3/portfolio#1]
Nice portfolio, I love the typography!

I was trying to follow you on social networks, but couldn't find a link to your twitter. Not sure if you use that or not, but if you do it might be worth putting it in the footer or something!

**Comment by jeddy3** [comment]
> Nice portfolio, I love the typography!

Thanks!

> I was trying to follow you on social networks... might be worth putting it in the footer..

Thanks for the suggestion, but I'm not on any social networks. You can reach me at my email address (which is on the portfolio) or on here :)
